### ISSUE TITLE
Request for working kernel config

### ISSUE THREAD

**Issue by drtyhlpr** [vfdev-5/qemu-rpi2-vexpress#1]
Hi, thank you very much for your github project,

I am currently trying to build the latest linux sources using:
vexpress_defconfig and olddefconfig

to get it running with latest qemu. your pre compiled kernel is running fine (thx) but is quite a few MB bigger than the default vexpress linux kernel I am building.

so no matter what i try (different configs, dtbs etc) I can not get my (cross)compiled kernel to boot on qemu (no graphical output at all / console same). I am a little bit out of ideas...

can you maybe also share the .config / a working .config? have you maybe experienced same problems with latest kernels ?

thank you!

**Comment by vfdev-5** [comment]
Hi,  you're welcome!

it's been a while that I did not check this project and probably I won't find the .config file.
Have you tried to build 4.4.1 kernel as described in [here](https://github.com/vfdev-5/qemu-rpi2-vexpress#linux-kernel-441-and-dtb) ? 
Which exact version (latest) of kernel are you trying to build? Maybe I can give a try if I have time.

**Comment by drtyhlpr** [comment]
hi, thanks for your fast reply.

I am trying to build https://github.com/raspberrypi/linux (latest stable 4.14.y). I tried the same config you described in you posting and extended it to module support and various other try out config parameters to get any output from the compiled kernel loaded with latest qemu.

It's hard for me to debug because I get 0 output from qemu loading the compiled kernels. (yeah if I dont find another way I tough about a gdb session. just feels like qemu tries to load the wrong zImage addr). I tried all the different arm7 dtbs etc. but 0 output (would love to see any error or dump).

some ideas:
- maybe a problem with the dtbs (not sure if the rpi linux kernel sources use different dtb settings etc)
- maybe a problem with the zImage format (the compiled zImage needs to be converted using rpi's "${KERNEL_DIR}/scripts/mkknlimg" to get it booted by rpi hardware) - i tried both formats (native zImage and mkknlimg-ed zImage) both did not work
- found no tool to print out loader addrs etc of the generated zImages (realy gdb aggain aahhh)

ps. I will post more output and try outs tomorrow if i find time
pps. currently trying to get versatile https://github.com/dhruvvyas90/qemu-rpi-kernel/tree/master/tools running (at least)
pps, I want to add this to a nice bootsrapping script (https://github.com/drtyhlpr/rpi23-gen-image)  and want to be flexible and not nailed to a specific kernel version

**Comment by vfdev-5** [comment]
@drtyhlpr I tried to recompile linux 4.4.1 kernel and reproduce rpi2 image emulation in qemu. I did it in a docker, but I have a problem to mount `Ubuntu Mate 16.04 armhf` image (.img) directly, so technically I can not reproduce my previous work. 
In parallel I also managed to compile kernel from https://github.com/raspberrypi/linux (latest tag: raspberrypi-kernel_1.20180924-1.tar.gz).

Concerning the 0 outputs, can you provide some details on how do you exactly use the scripts ?
For me, when I start `bash start.bash ubuntu-mate-16.04-desktop-armhf-raspberry-pi.img` I have a lot of verbose message on what's going on...

**Comment by drtyhlpr** [comment]
hi sorry for the delay.

I got it working now. I am not a expert in the linux kernel building and configuration file handling so I need to investigate this to fully understand the problem.

to get it working I just use the "vexpress_defconfig" without any user based kernel config. (so currently I am running vexpress_defconfig and olddefconfig - not even sure if this is needed). As soon as I add the mentioned kernel configuration parameters:

```
$ cat >> .config << EOF
> CONFIG_FHANDLE=y
> CONFIG_LBDAF=y
> EOF
```

I get an error about missing module support, fixing that within in the config will successfully generate the kernel image. But this image does not show any output on qemu gfx window or console.

I am just happy it works now. spend quite some time on this and will diff the config etc. soon.

I will update https://github.com/drtyhlpr/rpi23-gen-image to include QEMU support, or better said generate a image for QEMU static with /etc/fstab, ld.so.preload fixes applied. I started to add QEMU support to finally fix ENABLE_CRYPTFS "Enable full system encryption" images (initramfs troubles).

thanks for your help and ideas

**Comment by vfdev-5** [comment]
Glad you managed to do what you wanted. 

Anyway, I think I can create a branch in this repo with compiled rpi linux kernel (https://github.com/raspberrypi/linux) and script to reproduce it if somebody else will need this too.

I close the issue, feel free to reopen if you have some other problems :)
